### ISSUE TITLE
ERROR] [1676026053.971619]: Error processing request: field values[] must be unsigned integer type

### ISSUE THREAD

**Issue by Legendaryaaa** [mcsix/xela-server-ros#5] opened 2023-02-10 09:59 UTC
an@jing:~/project/tactile/src/xela_server$ rrosrun xela_server example.py
Traceback (most recent call last):
  File "/home/anjing/project/tactile/src/xela_server/example.py", line 17, in <module>
    service_example=srv(1, 3)
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_service.py", line 442, in __call__
    return self.call(*args, **kwds)
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_service.py", line 523, in call
    responses = transport.receive_once()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 742, in receive_once
    p.read_messages(b, msg_queue, sock) 
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_service.py", line 360, in read_messages
    self._read_ok_byte(b, sock)
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_service.py", line 343, in _read_ok_byte
    raise ServiceException("service [%s] responded with an error: %s"%(self.resolved_name, str))
rospy.service.ServiceException: service [/xServXYZ] responded with an error: b'error processing request: field values[] must be unsigned integer type'

**when I used xela server package to get uskin data,I got this mistake.
I have chaged code of  the shall  --tactile/src/xela_server/scripts/xela_server** 
#!/usr/bin/env bash
j="";
for arg in "$@"
do
    j="$j $arg";
done
/etc/xela/xela_server"$j" 

****because the mistake** command not found**,but why the value of sensor is not unsigned integer type'

**Comment by Legendaryaaa** [comment] 2023-02-10 10:22
an@jing:~/project/tactile$ rosservice call /xServXY 1 2
ERROR: service [/xServXY] responded with an error: b'error processing request: field values[] must be unsigned integer type'

**Comment by mcsix** [comment] 2023-02-11 15:04
The cause for this error is not clearly visible from this outtake.
To determine if the server is functioning correctly, can you leave xela_viz running when starting the ROS node? This way, it is possible to see if there's any error happening due to the initiation of the server via ROS.

The applications should be in a regular directory on PATH, i.e /usr/bin and not in /etc/xela, as the latter is for configuration and log files only. Also, what permissions do each of the directories and applications have?

On Monday, I will try to run a test on a work PC, as currently, I have no access to both the sensors or ROS.

Providing a xela_server log file would be beneficial for the investigation as well.

**Comment by mcsix** [comment] 2023-02-13 09:29
Based on the terminal output, we have set up a fresh Ubuntu 20.04 Virtual machine with ROS Noetic installed, similar to yours.
After installing catkin and setting up a catkin build environment, we added the xela_server package into the catkin workspace, both with and without the outer xela-server-ros directory and ran the ROS node with roslaunch xela_server service.launch
We also kept the visualization window open to monitor the activity from the xela_server app.
All sensor output was visible on our xela_viz window, and when we then ran the supplied example.py, it responded correctly and without any errors or warnings.

Therefore, please supply the following for further investigation:
- outtake of /etc/xela directory structure (run ls -R /etc/xela > xelaetc.txt for simplicity)
- outtake of your catkin workspace
- list of any files that you have edited with the edits present
- location and permissions of xela_server that is being used via ROS node
- all log files from /etc/xela/LOG (if the directory does not exist, make sure to give 777 permissions to the /etc/xela directory first)

Once we have the above information, we will do our best to replicate the situation and find a solution.

**Comment by mcsix** [comment] 2023-02-24 05:19
No required information was provided for over a week.
Closing as might be resolved. If not, could you open a new issue with the details noted in the later comments?

**Closed as completed by mcsix** 2023-02-24 05:19 UTC
Labels: bug, investigation required
